[package]
name = "treasurehole"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = [] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
bytebuffer = "0.2.1"
bytes = "*"
